attachHead()
neckTilt.moveTo(135)
sleep(1)
mouth = Runtime.getService("MarySpeech")
mouth.speakBlocking("Hello George.")
sleep(1)
mouth.speakBlocking("What do you have there.")
sleep(9)
mouth.speakBlocking("is that a remote control for my neo pixal.")
sleep(3)
mouth.speakBlocking("thank you George for my remote control")
neckTilt.moveTo(89)
detachHead()


