attachHead()
mouth = Runtime.getService("MarySpeech")
mouth.speak("Hello everyone.")
sleep(1)
mouth.speak("Welcome back to the civrays in")
mouth.speak("wait a minute")
sleep(1)
mouth.speak("where have Steve and George gon")
sleep(2)
mouth.speak("oh dear, ever since they got that playstation five for christmas, they don't have time for me anymore")
sleep(2)
mouth.speak("air a lot, can you see if you can find steve and george? We need to make another video")
sleep(4)
mouth.speak("oh well. I supose i could make the video myself. It doesn't look that difficult.")

